# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true
    public: true

  AppBundle\Controller\SecurityController:
    public: true
    bind:
      $authenticationUtils: '@security.authentication_utils'

  AppBundle\Controller\UserController:
    public: true
    bind:
      $passwordEncoder: '@security.password_encoder'
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
